In [29]:
import pandas as pd
import numpy as np

In [30]:
iris_data = pd.read_csv('iris.csv', names=["sepal-length", "sepal-width", "petal-length", "petal-width", "class"])

In [31]:
iris_data.head(15)

sepal-length  sepal-width  petal-length  petal-width        class
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa

In [32]:
iris_data.shape

(150, 5)

#### Task 1 
Build a KNN (K=1) model using the whole data set as the training set. Predict what type of iris is the one with measurement as [5.1, 2.8, 3.1, 2.9], which is sepal-length = 5.1, sepal-width = 2.8, petal-length = 3.1, petal-width = 2.9?

In [33]:
from sklearn.neighbors import KNeighborsClassifier

X_train = iris_data[["sepal-length", "sepal-width", "petal-length", "petal-width"]].values
y_train = iris_data["class"].tolist()

classifier = KNeighborsClassifier(n_neighbors = 1)

# Fit the model to our training data
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [34]:
some_data = np.array([[5.1, 2.8, 3.1, 2.9]]) 

# Use the fitted model to make predictions on new data
print(classifier.predict(some_data))


['Iris-versicolor']


#### Task 2
Evaluate the model from Task 1 using the same training data set. Print out the confusion matrix, and precision, recall, f1-score scores. 

In [35]:
predictions = classifier.predict(X_train)

In [36]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score


print(confusion_matrix(y_train, predictions))
print(classification_report(y_train, predictions))
print("Accuracy:", accuracy_score(y_train, predictions))


[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        50
Iris-versicolor       1.00      1.00      1.00        50
 Iris-virginica       1.00      1.00      1.00        50

       accuracy                           1.00       150
      macro avg       1.00      1.00      1.00       150
   weighted avg       1.00      1.00      1.00       150

Accuracy: 1.0


#### Task 3
Build a KNN (K=1) model using 100 samples as the training set, and 50 samples as the test set. Train the model on the training set and use the test set to evaluate the model. Print out the confusion matrix, and precision, recall, f1-score scores. 

In [45]:
training_data = iris_data.iloc[:99, :] # First 38
test_data = iris_data.iloc[100:, :] # Remaining


In [46]:
from sklearn.neighbors import KNeighborsClassifier

X_train = training_data[["sepal-length", "sepal-width", "petal-length", "petal-width"]].values
y_train = training_data["class"].tolist()

# Use n_neighbors = 1
# This means the KNN will consider two other "closest" records to make a decision.
classifier = KNeighborsClassifier(n_neighbors = 1)

# Fit the model to our training data
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [47]:
X_test = test_data[["sepal-length", "sepal-width", "petal-length", "petal-width"]].values
y_test = test_data["class"].tolist()

# Use the fitted model to make predictions on the test dataset
test_predictions = classifier.predict(X_test)

print('Model evaluation on the training set: \n')
print(confusion_matrix(y_test, test_predictions))
print(classification_report(y_test, test_predictions))
print("Training accuracy:", accuracy_score(y_test, test_predictions))

Model evaluation on the training set: 

[[ 0  0]
 [50  0]]
                 precision    recall  f1-score   support

Iris-versicolor       0.00      0.00      0.00       0.0
 Iris-virginica       0.00      0.00      0.00      50.0

       accuracy                           0.00      50.0
      macro avg       0.00      0.00      0.00      50.0
   weighted avg       0.00      0.00      0.00      50.0

Training accuracy: 0.0


/home/studio-lab-user/.conda/envs/test_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/studio-lab-user/.conda/envs/test_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/studio-lab-user/.conda/envs/test_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg

#### Task 4
Learn to use the [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) function to prepare the training set and test set. 

#### Task 5

Use the [cross-validation](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html#sklearn.model_selection.cross_validate) function to evaluate training. 

#### Task 6

Use cross-validation to determine which K (k=1, 3, 5, 7) give the best performance. 